[package]
name = "jit-sys"
description = "libjit in rust"
version = "0.1.0"
edition = "2018"
license = "MIT"
license-file = "LICENSE.txt"

repository = "https://github.com/MonliH/jit-sys"

[dependencies]

[build-dependencies]
bindgen = "0.59.1"
