[package]
name = "jit-sys"
description = "libjit in rust"
version = "0.1.0"
edition = "2018"
license = "MIT"

repository = "https://github.com/MonliH/jit-sys"

[dependencies]
libc = "*"

[build-dependencies]
bindgen = "0.59.1"
